### ISSUE TITLE
Teacher: relax requirement in smelodesousa/F5/5-brackets

### ISSUE THREAD

**Issue by grayswandyr** [learn-ocaml-community/teaching-feedback#1]
### Question?

Hi, thanks for these exercises. I was thinking the requirement of using a *list* accumulator for parentheses in `smelodesousa/F5/5-brackets` is a bit too strong. Using an integer accumulator is enough for this exercise, because there is only one type of symbol to follow. So perhaps it would be better to have only argument for function `verify`, to let the student devise his/her own implementation approach.

**Comment by erikmd** [comment]
Hi @grayswandyr! Thanks a lot for raising your question!
I Cc @smdsousa (the main author of this learn-ocaml exercise) in case he didn't receive a notification of this thread.

**Comment by smdsousa** [comment]
Hi all

We have proposed a PR with the change grayswandyr has suggested at the time
he raises his point.

In the very local context of my teaching, this exercise in this formulation
made sense this way. But not here anymore in a global repo. The improvment
suggestions made by grayswandryr are valid and where taken into account.

Best.
Smds

A domingo, 4/02/2024, 02:17, Erik Martin-Dorel ***@***.***>
escreveu:

**Comment by erikmd** [comment]
Ah OK! Thanks a lot Simão. Indeed, I've just seen (and reviewed) the PR https://github.com/ocaml-sf/learn-ocaml-corpus/pull/40.
I propose we close this question as soon as the PR is integrated.
Cheers, Erik
